---
vEOS1:
  hostname: 192.168.0.101
  groups:
    - spines
vEOS2:
  hostname: 192.168.0.102
  groups:
    - spines
vEOS3:
  hostname: 192.168.0.103
  groups:
    - leafs
vEOS4:
  hostname: 192.168.0.103
  groups:
    - leafs